### ISSUE TITLE
Add Python linting workflow

### ISSUE THREAD

**Issue by AnsahMohammad** [abdullahkhalids/qecft#11]
To ensure consistent adherence to the code standards and improve the overall quality of the codebase, implement a linting workflow that automatically checks for code conformity during pushes or pull requests (PRs).

Expected Configurations:
Code format provider: `autopep8`
Maximum allowed line length: `79`
Convention for lint docstring: `NumPy`

**Comment by abdullahkhalids** [comment]
Thanks. Everything looks good.
