### ISSUE TITLE
Typo in Chapter 2

### ISSUE THREAD

**Issue by rajkk1** [abdullahkhalids/qecft#15]
In chapter 2.1, the original line reads

For example, if the corrupted code-string was 101110111, then using the same algorithm Bob infers that that message was 110.

the line should read

For example, if the corrupted code-string was 101110111, then using the same algorithm Bob infers that that message was 111.

**Comment by abdullahkhalids** [comment]
Thanks for the correction. I will update soon.

**Comment by abdullahkhalids** [comment]
Fixed in the latest version. Thanks.
