### ISSUE TITLE
Forum for solutions

### ISSUE THREAD

**Issue by abdullahkhalids** [abdullahkhalids/qecft#2]
The book has many tasks for the user to do. Instead of providing solutions, I would like to create a forum associated with the book for  discussing solutions to these tasks.

To this end, we need to

* Select a simple forum system. Even a commenting system would work well.
* For each Task, create a page for discussing its solutions.
* Link to this page from the Task.

For the system, some nice features would be
* Written in python or similar language, so its easy for me to make changes.
* Doesn't require logins because I don't want to store user data. Just enter your name and email and submit a comment. This makes GDPR compliance easy because we are storing minimal data, but does cause issues with users wanting to delete or edit their answers.
* Threaded replies
* Voting, and sorting by voting.

 Currently leaning towards [isso](https://github.com/posativ/isso/). But open to suggestions to alternates.

To complete this issue, please

1. Start a discussion here on the details of the system. Please only start work once you are assigned to this issue.
2. Create an install script for all necessary software and their configuration on a standard ubuntu LTS server.
3. Some script to create a page for each task and link to that page from within the notebooks.

A small team working on this team is welcome.

**Comment by devilkiller-ag** [comment]
Hi, Can I tackle this issue?

**Comment by AnsahMohammad** [comment]
I would be happy to work on this. I am open to collaborating with a small team if anyone else joins.

**Comment by abdullahkhalids** [comment]
@AnsahMohammad Thanks for showing interest. As, this is a fairly complex problem, I would like to discuss before assigning. 

Given my vision, do you have any other ideas of setting up the system besides isso? I am very open to novel ideas. Any main problems you foresee with this?

**Comment by AnsahMohammad** [comment]
No, I haven't worked with any other forum systems before. We'll proceed with isso as the chosen system. One of the problems I foresee is the integration process.

**Comment by alt-shreya** [comment]
@AnsahMohammad I would like to work on this as well. Could we team up?

**Comment by AnsahMohammad** [comment]
@alt-shreya yup, sure 👍

**Comment by ashmitjsg** [comment]
Hi @abdullahkhalids , I haven't worked on Isso before, but I tried to learn about it. As far as I have discovered, we need to add the Isso JavaScript code snippet to our HTML pages where we want the commenting system to appear.  For each task, we can create separate HTML pages where users can discuss their solutions. These pages can be static HTML files or dynamically generated using our preferred web framework.  Within the book we have to add links from each task to its respective discussion page. Users can click on these links to access the discussion area for a specific task and submit their comments or solutions. Can I work on this issue?

**Comment by abdullahkhalids** [comment]
Okay great. Now we have three interested people. @AnsahMohammad and @alt-shreya are you open to a third? You are fully free to say no.

**Comment by AnsahMohammad** [comment]
Yes, I'm okay with it

**Comment by alt-shreya** [comment]
i'm okay with it

**Comment by aryanguptaaa** [comment]
Hi @abdullahkhalids , I am somewhat familiar with Isso and i also want to work on this issue. Can I also join the team ?

**Comment by ashmitjsg** [comment]
Yeah, that would be great 👍🏻

**Comment by AnsahMohammad** [comment]
I believe that we won't require more than three members to complete this project. @abdullahkhalids, I would appreciate hearing your thoughts on this matter.

**Comment by alt-shreya** [comment]
Agreed with @AnsahMohammad. Would still like to hear from @abdullahkhalids .

**Comment by abdullahkhalids** [comment]
I think three is a healthy number.  @aryanguptaaa I don't think there is space here - thank you for understanding.

For the remaining three, please remember that your individual contributions are most easily measured by what you committed to the Pull request. 

Good luck.

**Comment by ashmitjsg** [comment]
@abdullahkhalids, how should we start, should I create a branch and pr for this and then everyone can contribute to the same branch?

**Comment by devilkiller-ag** [comment]
@abdullahkhalids, how should we start, should I create a branch and pr for this and then everyone can contribute to the same branch?

**Comment by abdullahkhalids** [comment]
I think that is the best way.

**Comment by ashmitjsg** [comment]
I have created a branch `forum`, @alt-shreya @AnsahMohammad you both can contribute to the same branch. Before proceeding further should we divide the tasks among us?

**Comment by AnsahMohammad** [comment]
Cool !. Does everyone have qiskit slack ? Maybe we can coordinate via slack.

**Comment by abdullahkhalids** [comment]
You can also just start a discord thread.

**Comment by ashmitjsg** [comment]
I am fine with both.

**Comment by abdullahkhalids** [comment]
I just asked this over on isso https://github.com/posativ/isso/discussions/956 Posting here to keep a record.

**Comment by ashmitjsg** [comment]
Once @alt-shreya and @AnsahMohammad , confirms I will make slack or discord thread, whatever they are comfortable with.

**Comment by AnsahMohammad** [comment]
@devilkiller-ag I'm okay with both 👍

**Comment by AnsahMohammad** [comment]
@devilkiller-ag, give @alt-shreya and me access to the forked repo "devilkiller-ag/qecft" so we can start.

**Comment by ashmitjsg** [comment]
@AnsahMohammad Done

**Comment by AnsahMohammad** [comment]
@devilkiller-ag Have you made the Discord thread yet?

**Comment by ashmitjsg** [comment]
@abdullahkhalids I didn't get confirmation from @alt-shreya, on which platform she wants to continue. But let's not waste time anymore I am creating a discord thread. Kindly share your discord username.

**Comment by AnsahMohammad** [comment]
My username : "Ansaaaa#2539"
@alt-shreya, you can join in the middle as we're starting now due to time constraints. Please share your Discord ID or suggest any other platform you're comfortable with.

**Comment by ashmitjsg** [comment]
> My username : "Ansaaaa#2539"
> @alt-shreya, you can join in the middle as we're starting now due to time constraints. Please share your Discord ID or suggest any other platform you're comfortable with.

- I have sent you a request on discord. @abdullahkhalids Will you also be joining to coordinate with us?

**Comment by abdullahkhalids** [comment]
My username is `Abdullah Khalid#0684` Easy to find me on the UnitaryFund channel. Please add me.

**Comment by abdullahkhalids** [comment]
@AnsahMohammad Thanks for completing the issue. Good luck with the rest of the Hackathon.
