### ISSUE TITLE
 Implementation of color codes

### ISSUE THREAD

**Issue by abdullahkhalids** [abdullahkhalids/qecft#3]
A future chapter of the book will discuss color codes.

Implement the syndrome measurements for the [color code](https://errorcorrectionzoo.org/c/color) in [stac](https://github.com/abdullahkhalids/stac). In particular, we are looking for an implementation of the 2D 4.8.8 color code family (see [here](https://arxiv.org/pdf/1108.5738.pdf))

Please see how [standard syndrome measurements](https://github.com/abdullahkhalids/stac/blob/b48947207dcca3e472729dfbf74e787f9538eed9/stac/code.py#LL777C15-L777C15) are implemented.

~~This is a good opportunity to use coordinate based addressing of qubits: see last section of this [guide](https://github.com/abdullahkhalids/stac/wiki/guide). I also wrote a detailed explanation for how to do this for surface codes [here](https://github.com/abdullahkhalids/qecft/pull/5#issuecomment-1569370695).~~

To complete this issue, please create a .py file in the drafts folder that contains a function `_color_codes_syndrome_measurements`.

**Comment by victor-onofre** [comment]
Hi! I will try to solve this issue during the UnitaryHack

**Comment by abdullahkhalids** [comment]
@victor-onofre Thanks. Should I assign you to this bounty?

**Comment by victor-onofre** [comment]
Yes, please. At the moment, I'm reading the book and doing the tasks. 
Thanks!

**Comment by abdullahkhalids** [comment]
I have assigned you. Good luck. If you have any questions, please feel free to ask here.

**Comment by victor-onofre** [comment]
I have a couple of questions. The Steane code is the smallest 2D color code, already implemented in stac. In this case, Is the task to create a more general function for color codes? How general does it need to be the function? I'm now reading this [paper](https://arxiv.org/pdf/1108.5738.pdf) as a reference. Do you have other references that may help me?

Also, I have checked almost all the book. You have done an amazing job, I love it! I have noticed some typos and small errors. Maybe I can help in that part also once this issue is finished. 

Thanks!

**Comment by abdullahkhalids** [comment]
>  Is the task to create a more general function for color codes? 

We want a way to generate a whole family of color codes. There are many such families. 

Lets just do the 2D 4.8.8 color code family for this issue. You can see in your reference paper (Fig 2), that this family of codes with parameters $[[d^2/2 + d - 1/2, 1, d]]$. Our goal is to write a function `color_code_488(d)`, where the distance, `d`,  is an odd integer. For every such `d` the function should output the syndrome measurement circuit for the corresponding code.

Additional references: a later [paper](https://arxiv.org/pdf/1407.5103.pdf) by the same authors, the original [paper](https://arxiv.org/pdf/quant-ph/0605138.pdf) on color codes, [quantum error correction zoo page](https://errorcorrectionzoo.org/c/color#citation-3)

But really you don't need many references. You just need to look up the geometry of the [4.8.8 tiling](https://en.wikipedia.org/wiki/List_of_Euclidean_uniform_tilings) and just go from there.

 > Also, I have checked almost all the book. You have done an amazing job, I love it! I have noticed some typos and small errors. Maybe I can help in that part also once this issue is finished.

Thank you. Its still work in progress. I do have a long list of typos and errors that I am currently working on fixing.

**Comment by victor-onofre** [comment]
Great! Now it is more clear. I will continue working on this over the weekend.

Thanks for the help!

**Comment by abdullahkhalids** [comment]
For the other issue for surface codes, I wrote down [this](https://github.com/abdullahkhalids/qecft/pull/5#issuecomment-1569370695) detailed explanation on how to write the circuit.

I think you should take a look at it.

**Comment by abdullahkhalids** [comment]
@victor-onofre are you still working on this?

**Comment by victor-onofre** [comment]
Hi @abdullahkhalids, yes I will try to finish this week. Maybe I'm getting too much into the theory. I will post some questions later. 

Thanks!

**Comment by abdullahkhalids** [comment]
This is a fairly difficult task, and more than I anticipated it to be.

Can you tell me where you are stuck, or what are things you can't figure out, so I can help you?

You can also message me on discord at `Abdullah Khalid#0684`.

**Comment by victor-onofre** [comment]
I will send you a message on Discord

**Comment by abdullahkhalids** [comment]
I have sent you the new guide on discord because it  won't let me upload ipynb here.

Please note that I am simplifying the issue requirements, and removing the bit about coordinate based addressing as that is too difficult.

Just create the syndrome measurement circuit as explained in the notebook I sent you.

**Comment by abdullahkhalids** [comment]
Thank you so much for the hard work.
